# Generated by Django 2.1 on 2019-06-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190618_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='newskzmedia',
            name='newsKZ',
        ),
        migrations.RemoveField(
            model_name='newskzvideo',
            name='newKZ',
        ),
        migrations.RemoveField(
            model_name='order',
            name='room',
        ),
        migrations.DeleteModel(
            name='NewsKZ',
        ),
        migrations.DeleteModel(
            name='NewsKZMedia',
        ),
        migrations.DeleteModel(
            name='NewsKZVideo',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
