# Generated by Django 2.1 on 2019-06-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190628_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommedia',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomMedia',
        ),
    ]
