# Generated by Django 2.1 on 2019-06-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190628_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldbalance',
            name='timestamp',
            field=models.DateField(verbose_name='Дата замера'),
        ),
    ]
