# Generated by Django 2.1 on 2019-07-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190630_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldbalance',
            name='ansagan_brutto',
            field=models.FloatField(db_index=True, default=0, verbose_name='Весы по Ансаган (брутто)'),
        ),
        migrations.AddField(
            model_name='fieldbalance',
            name='ansagan_density',
            field=models.FloatField(db_index=True, default=0, verbose_name='Весы по Ансаган (плотность)'),
        ),
        migrations.AddField(
            model_name='fieldbalance',
            name='ansagan_netto',
            field=models.FloatField(db_index=True, default=0, verbose_name='Весы по Ансаган (нетто)'),
        ),
        migrations.AddField(
            model_name='fieldbalance',
            name='transport_brutto',
            field=models.FloatField(db_index=True, default=0, verbose_name='Автомобильные весы (брутто)'),
        ),
        migrations.AddField(
            model_name='fieldbalance',
            name='transport_density',
            field=models.FloatField(db_index=True, default=0, verbose_name='Автомобильные весы (плотность)'),
        ),
        migrations.AddField(
            model_name='fieldbalance',
            name='transport_netto',
            field=models.FloatField(db_index=True, default=0, verbose_name='Автомобильные весы (нетто)'),
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='ansagan_balance',
            field=models.FloatField(db_index=True, default=0, verbose_name='Весы по Ансаган (жидкость)'),
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='transport_balance',
            field=models.FloatField(db_index=True, default=0, verbose_name='Автомобильные весы (жидкость)'),
        ),
    ]
