# Generated by Django 2.1 on 2019-08-12 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_wellmatrix_gas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_time', models.FloatField(default=0, verbose_name='Время замера')),
                ('teh_rej_water', models.FloatField(default=0, verbose_name='Обводненность')),
                ('fluid', models.FloatField(default=0, verbose_name='Замерная жидкость')),
                ('density', models.FloatField(default=0, verbose_name='Плотность')),
                ('stop_time', models.FloatField(default=0, verbose_name='Простои')),
                ('timestamp', models.DateTimeField(verbose_name='Дата замера')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_wells', to='main.Well')),
            ],
            options={
                'verbose_name': 'Обратный расчет',
                'verbose_name_plural': 'Обратные расчеты',
            },
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='agzu_fluid',
            field=models.FloatField(default=0, verbose_name='Замер жидкости по скважинам'),
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='agzu_oil',
            field=models.FloatField(default=0, verbose_name='Замер нефти по скважинам'),
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='ansagan_balance',
            field=models.FloatField(default=0, verbose_name='Весы по Ансаган (жидкость)'),
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='ansagan_brutto',
            field=models.FloatField(default=0, verbose_name='Весы по Ансаган (брутто)'),
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='ansagan_density',
            field=models.FloatField(default=0, verbose_name='Весы по Ансаган (плотность)'),
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='ansagan_netto',
            field=models.FloatField(default=0, verbose_name='Весы по Ансаган (нетто)'),
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='teh_rej_fluid',
            field=models.FloatField(default=0, verbose_name='Замер по Тех. жидкости'),
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='teh_rej_oil',
            field=models.FloatField(default=0, verbose_name='Замер по Тех. нефти'),
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='transport_balance',
            field=models.FloatField(default=0, verbose_name='Автомобильные весы (жидкость)'),
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='transport_brutto',
            field=models.FloatField(default=0, verbose_name='Автомобильные весы (брутто)'),
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='transport_density',
            field=models.FloatField(default=0, verbose_name='Автомобильные весы (плотность)'),
        ),
        migrations.AlterField(
            model_name='fieldbalance',
            name='transport_netto',
            field=models.FloatField(default=0, verbose_name='Автомобильные весы (нетто)'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='fluid',
            field=models.FloatField(default=0, verbose_name='Замерная жидкость'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='gas',
            field=models.FloatField(default=0, verbose_name='Газ'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='teh_rej_fluid',
            field=models.FloatField(default=0, verbose_name='Техрежим жидкости'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='teh_rej_oil',
            field=models.FloatField(default=0, verbose_name='Техрежим нефти'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='teh_rej_water',
            field=models.FloatField(default=0, verbose_name='Обводненность'),
        ),
    ]
