# Generated by Django 2.1 on 2019-08-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190812_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reversecalculation',
            name='timestamp',
            field=models.DateField(verbose_name='Дата замера'),
        ),
    ]
