# Generated by Django 2.1 on 2019-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190813_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='reversecalculation',
            name='teh_rej_fluid',
            field=models.FloatField(default=0, verbose_name='Техрежим жидкости'),
        ),
        migrations.AddField(
            model_name='reversecalculation',
            name='teh_rej_oil',
            field=models.FloatField(default=0, verbose_name='Техрежим нефти'),
        ),
    ]
