# Generated by Django 2.1 on 2019-08-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190822_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluid_beg', models.FloatField(default=0, verbose_name='Жидкость на начало')),
                ('fluid_end', models.FloatField(default=0, verbose_name='Жидкость на конец')),
                ('teh_rej_water', models.FloatField(default=0, verbose_name='Обводненность')),
                ('fluid_brutto', models.FloatField(default=0, verbose_name='Добыча по весам (брутто)')),
                ('needs', models.FloatField(default=0, verbose_name='Собственные нужды')),
                ('pump', models.FloatField(default=0, verbose_name='Откачки воды')),
                ('timestamp', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Замерная добыча',
                'verbose_name_plural': 'Замерные добычи',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_time', models.FloatField(default=0, verbose_name='Время замера')),
                ('teh_rej_fluid', models.FloatField(default=0, verbose_name='Техрежим жидкости')),
                ('teh_rej_oil', models.FloatField(default=0, verbose_name='Техрежим нефти')),
                ('teh_rej_water', models.FloatField(default=0, verbose_name='Обводненность')),
                ('fluid', models.FloatField(default=0, verbose_name='Замерная жидкость')),
                ('gas', models.FloatField(default=0, verbose_name='Газ')),
                ('density', models.FloatField(default=0, verbose_name='Плотность')),
                ('stop_time', models.FloatField(default=0, verbose_name='Простои')),
                ('timestamp', models.DateField(verbose_name='Дата')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_wells', to='main.Well')),
            ],
            options={
                'verbose_name': 'Замерная добыча',
                'verbose_name_plural': 'Замерные добычи',
            },
        ),
        migrations.RemoveField(
            model_name='reversecalculation',
            name='well',
        ),
        migrations.AddField(
            model_name='field',
            name='density',
            field=models.FloatField(default=0.8, verbose_name='Плотность'),
        ),
        migrations.DeleteModel(
            name='ReverseCalculation',
        ),
        migrations.AddField(
            model_name='parkproduction',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_fields', to='main.Field'),
        ),
    ]
