# Generated by Django 2.1 on 2019-08-26 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20190826_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluid', models.FloatField(default=0, verbose_name='Замерная жидкость')),
                ('oil', models.FloatField(default=0, verbose_name='Замерная нефть')),
                ('park_fluid', models.FloatField(default=0, verbose_name='Парковая жидкость')),
                ('park_oil', models.FloatField(default=0, verbose_name='Парковая нефть')),
                ('coeff_fluid', models.FloatField(default=0, verbose_name='Парковый коэф. жидкости')),
                ('coeff_oil', models.FloatField(default=0, verbose_name='Парковый коэф. нефти')),
                ('timestamp', models.DateField(verbose_name='Дата')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_fields', to='main.Field')),
            ],
            options={
                'verbose_name': 'Обратный расчет',
                'verbose_name_plural': 'Обратные расчеты',
            },
        ),
    ]
