# Generated by Django 2.1 on 2019-08-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_reversecalculation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkproduction',
            options={'verbose_name': 'Парковая добыча', 'verbose_name_plural': 'Парковые добычи'},
        ),
    ]
