# Generated by Django 2.1 on 2019-09-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190906_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='timestamp',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
