# Generated by Django 2.1 on 2019-09-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20190906_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='production',
            name='stop_init',
            field=models.CharField(choices=[('Механик', 'Механик'), ('Технолог', 'Технолог'), ('Электрик', 'Электрик'), ('КИП', 'КИП')], default='Механик', max_length=20, verbose_name='Инициатор остановки'),
        ),
        migrations.AddField(
            model_name='production',
            name='stop_reason',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Причина остановки'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='well',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
