# Generated by Django 2.1 on 2019-09-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20190916_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='stop_init',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Инициатор остановки'),
        ),
    ]
