# Generated by Django 2.1 on 2019-10-01 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20190916_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Способ эксплуатации')),
                ('thp', models.FloatField(default=0, verbose_name='Ртр')),
                ('annulus', models.FloatField(default=0, verbose_name='Рзатр')),
                ('flow_line', models.FloatField(default=0, verbose_name='Рвык')),
                ('tyct', models.FloatField(default=0, verbose_name='THT')),
                ('choke_size', models.FloatField(default=0, verbose_name='Choke size')),
                ('replacement', models.DateField(blank=True, null=True, verbose_name='Дата замены')),
                ('operated_time', models.FloatField(default=0, verbose_name='Время работы')),
                ('emir_oil', models.FloatField(default=0, verbose_name='Емир Ойл')),
                ('otbivka', models.DateField(blank=True, null=True, verbose_name='Дата отбивки')),
                ('fluid', models.FloatField(default=0, verbose_name='Жидкость, м3')),
                ('fluid_tonn', models.FloatField(default=0, verbose_name='Жидкость, т')),
                ('teh_rej_water', models.FloatField(default=0, verbose_name='Обводненность')),
                ('oil', models.FloatField(default=0, verbose_name='Нефть, м3')),
                ('oil_tonn', models.FloatField(default=0, verbose_name='Нефть, т')),
                ('daily_prod', models.FloatField(default=0, verbose_name='Суточная добыча, bbl')),
                ('gor', models.FloatField(default=0, verbose_name='Газовый фактор')),
                ('measurement', models.DateField(blank=True, null=True, verbose_name='Дата замера')),
                ('water_drainage', models.FloatField(default=0, verbose_name='Слив воды')),
                ('stop_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='Время остановки')),
                ('stop_date', models.DateField(blank=True, null=True, verbose_name='Дата остановки')),
                ('stop_reason', models.CharField(blank=True, max_length=30, null=True, verbose_name='Причина остановки')),
                ('research', models.CharField(blank=True, max_length=50, null=True, verbose_name='Исследования')),
                ('result', models.CharField(blank=True, max_length=50, null=True, verbose_name='Результат')),
                ('spusk', models.DateField(blank=True, null=True, verbose_name='Дата спуска')),
                ('tool_depth', models.FloatField(default=0, verbose_name='Глубина спуска')),
                ('comments', models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание')),
                ('timestamp', models.DateField(verbose_name='Дата')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_wells', to='main.Well')),
            ],
            options={
                'verbose_name': 'Сводный отчет',
                'verbose_name_plural': 'Сводные отчеты',
            },
        ),
        migrations.RemoveField(
            model_name='reversecalculation',
            name='field',
        ),
        migrations.DeleteModel(
            name='ReverseCalculation',
        ),
    ]
